package utils

import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent
import java.awt.event.KeyEvent

object KeyEventMapper {

    private val awtToNativeMap = mapOf(
        KeyEvent.VK_ENTER to NativeKeyEvent.VC_ENTER,
        KeyEvent.VK_BACK_SPACE to NativeKeyEvent.VC_BACKSPACE,
        KeyEvent.VK_TAB to NativeKeyEvent.VC_TAB,
        KeyEvent.VK_CLEAR to NativeKeyEvent.VC_CLEAR,
        KeyEvent.VK_SHIFT to NativeKeyEvent.VC_SHIFT,
        KeyEvent.VK_CONTROL to NativeKeyEvent.VC_CONTROL,
        KeyEvent.VK_ALT to NativeKeyEvent.VC_ALT,
        KeyEvent.VK_PAUSE to NativeKeyEvent.VC_PAUSE,
        KeyEvent.VK_CAPS_LOCK to NativeKeyEvent.VC_CAPS_LOCK,
        KeyEvent.VK_ESCAPE to NativeKeyEvent.VC_ESCAPE,
        KeyEvent.VK_SPACE to NativeKeyEvent.VC_SPACE,
        KeyEvent.VK_PAGE_UP to NativeKeyEvent.VC_PAGE_UP,
        KeyEvent.VK_PAGE_DOWN to NativeKeyEvent.VC_PAGE_DOWN,
        KeyEvent.VK_END to NativeKeyEvent.VC_END,
        KeyEvent.VK_HOME to NativeKeyEvent.VC_HOME,
        KeyEvent.VK_LEFT to NativeKeyEvent.VC_LEFT,
        KeyEvent.VK_UP to NativeKeyEvent.VC_UP,
        KeyEvent.VK_RIGHT to NativeKeyEvent.VC_RIGHT,
        KeyEvent.VK_DOWN to NativeKeyEvent.VC_DOWN,
        KeyEvent.VK_COMMA to NativeKeyEvent.VC_COMMA,
        KeyEvent.VK_MINUS to NativeKeyEvent.VC_MINUS,
        KeyEvent.VK_PERIOD to NativeKeyEvent.VC_PERIOD,
        KeyEvent.VK_SLASH to NativeKeyEvent.VC_SLASH,
        KeyEvent.VK_0 to NativeKeyEvent.VC_0,
        KeyEvent.VK_1 to NativeKeyEvent.VC_1,
        KeyEvent.VK_2 to NativeKeyEvent.VC_2,
        KeyEvent.VK_3 to NativeKeyEvent.VC_3,
        KeyEvent.VK_4 to NativeKeyEvent.VC_4,
        KeyEvent.VK_5 to NativeKeyEvent.VC_5,
        KeyEvent.VK_6 to NativeKeyEvent.VC_6,
        KeyEvent.VK_7 to NativeKeyEvent.VC_7,
        KeyEvent.VK_8 to NativeKeyEvent.VC_8,
        KeyEvent.VK_9 to NativeKeyEvent.VC_9,
        KeyEvent.VK_SEMICOLON to NativeKeyEvent.VC_SEMICOLON,
        KeyEvent.VK_EQUALS to NativeKeyEvent.VC_EQUALS,
        KeyEvent.VK_A to NativeKeyEvent.VC_A,
        KeyEvent.VK_B to NativeKeyEvent.VC_B,
        KeyEvent.VK_C to NativeKeyEvent.VC_C,
        KeyEvent.VK_D to NativeKeyEvent.VC_D,
        KeyEvent.VK_E to NativeKeyEvent.VC_E,
        KeyEvent.VK_F to NativeKeyEvent.VC_F,
        KeyEvent.VK_G to NativeKeyEvent.VC_G,
        KeyEvent.VK_H to NativeKeyEvent.VC_H,
        KeyEvent.VK_I to NativeKeyEvent.VC_I,
        KeyEvent.VK_J to NativeKeyEvent.VC_J,
        KeyEvent.VK_K to NativeKeyEvent.VC_K,
        KeyEvent.VK_L to NativeKeyEvent.VC_L,
        KeyEvent.VK_M to NativeKeyEvent.VC_M,
        KeyEvent.VK_N to NativeKeyEvent.VC_N,
        KeyEvent.VK_O to NativeKeyEvent.VC_O,
        KeyEvent.VK_P to NativeKeyEvent.VC_P,
        KeyEvent.VK_Q to NativeKeyEvent.VC_Q,
        KeyEvent.VK_R to NativeKeyEvent.VC_R,
        KeyEvent.VK_S to NativeKeyEvent.VC_S,
        KeyEvent.VK_T to NativeKeyEvent.VC_T,
        KeyEvent.VK_U to NativeKeyEvent.VC_U,
        KeyEvent.VK_V to NativeKeyEvent.VC_V,
        KeyEvent.VK_W to NativeKeyEvent.VC_W,
        KeyEvent.VK_X to NativeKeyEvent.VC_X,
        KeyEvent.VK_Y to NativeKeyEvent.VC_Y,
        KeyEvent.VK_Z to NativeKeyEvent.VC_Z,
        KeyEvent.VK_OPEN_BRACKET to NativeKeyEvent.VC_OPEN_BRACKET,
        KeyEvent.VK_BACK_SLASH to NativeKeyEvent.VC_BACK_SLASH,
        KeyEvent.VK_CLOSE_BRACKET to NativeKeyEvent.VC_CLOSE_BRACKET,
        KeyEvent.VK_SEPARATOR to NativeKeyEvent.VC_SEPARATOR,
        KeyEvent.VK_DELETE to NativeKeyEvent.VC_DELETE,
        KeyEvent.VK_NUM_LOCK to NativeKeyEvent.VC_NUM_LOCK,
        KeyEvent.VK_SCROLL_LOCK to NativeKeyEvent.VC_SCROLL_LOCK,
        KeyEvent.VK_F1 to NativeKeyEvent.VC_F1,
        KeyEvent.VK_F2 to NativeKeyEvent.VC_F2,
        KeyEvent.VK_F3 to NativeKeyEvent.VC_F3,
        KeyEvent.VK_F4 to NativeKeyEvent.VC_F4,
        KeyEvent.VK_F5 to NativeKeyEvent.VC_F5,
        KeyEvent.VK_F6 to NativeKeyEvent.VC_F6,
        KeyEvent.VK_F7 to NativeKeyEvent.VC_F7,
        KeyEvent.VK_F8 to NativeKeyEvent.VC_F8,
        KeyEvent.VK_F9 to NativeKeyEvent.VC_F9,
        KeyEvent.VK_F10 to NativeKeyEvent.VC_F10,
        KeyEvent.VK_F11 to NativeKeyEvent.VC_F11,
        KeyEvent.VK_F12 to NativeKeyEvent.VC_F12,
        KeyEvent.VK_PRINTSCREEN to NativeKeyEvent.VC_PRINTSCREEN,
        KeyEvent.VK_INSERT to NativeKeyEvent.VC_INSERT,
        KeyEvent.VK_HELP to NativeKeyEvent.VC_SUN_HELP,
        KeyEvent.VK_META to NativeKeyEvent.VC_META,
        KeyEvent.VK_BACK_QUOTE to NativeKeyEvent.VC_BACKQUOTE,
        KeyEvent.VK_QUOTE to NativeKeyEvent.VC_QUOTE,
        KeyEvent.VK_UP to NativeKeyEvent.VC_UP,
        KeyEvent.VK_DOWN to NativeKeyEvent.VC_DOWN,
        KeyEvent.VK_LEFT to NativeKeyEvent.VC_LEFT,
        KeyEvent.VK_RIGHT to NativeKeyEvent.VC_RIGHT,
    )

    fun awtToNative(awtKeyCode: Int): Int? {
        return awtToNativeMap[awtKeyCode]
    }
}